### ISSUE TITLE
Joplin Freezes after clicking in MD editor

### ISSUE THREAD

**Issue by Z0pyrus** [ylc395/joplin-plugin-better-markdown-viewer#4]
I'm experiencing an Issue, that when I klick or mark text in the Markdown segment, Joplin freezes. I think this is happening because my Database is Encrypted?

Here is the log:

```
022-05-31 18:01:22: joplin.plugins: "Starting plugin: ylc395.joplinOcr"
2022-05-31 18:01:22: SpellCheckerServiceDriverNative: "Set effective language from "de" to "de""
2022-05-31 18:01:24: joplin.plugins: "Starting plugin: ylc395.noteLinkSystem"
2022-05-31 18:01:24: joplin.plugins: "Starting plugin: ylc395.pagesPublisher"
2022-05-31 18:01:25: models/Setting: "Could not set setting on the keychain. Will be saved to database instead: plugin-ylc395.pagesPublisher.githubToken:", "Error: Password is required.
Error: Password is required.
    at checkRequired (F:\Programms\Joplin\resources\app.asar\node_modules\keytar\lib\keytar.js:5:11)
    at Object.setPassword (F:\Programms\Joplin\resources\app.asar\node_modules\keytar\lib\keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainService.js:51:32)
    at Generator.next (<anonymous>)"
2022-05-31 18:01:26: joplin.plugins: "Finished running onStart handler: ylc395.pagesPublisher (Took 2202ms)"
2022-05-31 18:01:26: joplin.plugins: "Finished running onStart handler: ylc395.joplinOcr (Took 3958ms)"
2022-05-31 18:01:28: models/Setting: "Could not save settings", "Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-ylc395.pagesPublisher.githubToken,
Code: SQLITE_CONSTRAINT
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-ylc395.pagesPublisher.githubToken,
    at DatabaseDriverNode.sqliteErrorToJsError (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:34:30)
    at JoplinDatabase.<anonymous> (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:133:36)
    at Generator.throw (<anonymous>)
    at rejected (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-31 18:01:29: joplin.plugins: "Finished running onStart handler: ylc395.noteLinkSystem (Took 5379ms)"
2022-05-31 18:01:30: models/Setting: "Could not set setting on the keychain. Will be saved to database instead: plugin-ylc395.pagesPublisher.githubToken:", "Error: Password is required.
Error: Password is required.
    at checkRequired (F:\Programms\Joplin\resources\app.asar\node_modules\keytar\lib\keytar.js:5:11)
    at Object.setPassword (F:\Programms\Joplin\resources\app.asar\node_modules\keytar\lib\keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (F:\Programms\Joplin\resources\app.asar\node_modules\@joplin\lib\services\keychain\KeychainService.js:51:32)
    at Generator.next (<anonymous>)"
2022-05-31 18:01:39: "ResourceService::indexNoteResources: Start"
2022-05-31 18:01:40: "ResourceService::indexNoteResources: Completed"
2022-05-31 18:01:40: "ResourceService::deleteOrphanResources:", "[]"
```

I have several extensions installed. 
Joplin Version: 2.7.15 (prod, win32)
Better Markdown Viewer: v2.0.4

**Comment by ylc395** [comment]
Seems to incompatible with OCR-plugin: https://github.com/ylc395/joplin-plugin-ocr/issues/5#issuecomment-1220827594
